# Generated by Django 4.2.6 on 2023-10-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wojewodztwo', models.CharField(max_length=45)),
                ('kodPocztowy', models.CharField(max_length=45)),
                ('nrDomu', models.CharField(max_length=45)),
                ('nrLokalu', models.CharField(max_length=45)),
                ('miejscowosc', models.CharField(max_length=45)),
                ('ulica', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('pseudonim', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('nrTelefonu', models.CharField(max_length=45)),
                ('dataUrodzenia', models.DateField()),
                ('login', models.CharField(max_length=45)),
                ('haslo', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=45)),
                ('autor', models.CharField(max_length=45)),
                ('dataPublikacji', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Opinie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(max_length=2)),
                ('komentarz', models.TextField(max_length=200)),
                ('dataDodania', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusKsiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaStatusu', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='StatusZamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='SzczegolyZamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cenaNetto', models.CharField(max_length=45)),
                ('cenaBrutto', models.CharField(max_length=45)),
                ('ilosc', models.CharField(max_length=45)),
                ('statusZamowienia', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Wydawnictwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataZamowienia', models.DateField()),
            ],
        ),
    ]
