# Generated by Django 4.2.6 on 2023-11-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mojaKsiegarnia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ksiazka',
            options={'ordering': ('tytul',)},
        ),
    ]
