# Generated by Django 4.2.7 on 2024-01-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='order_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('PD', 'W trakcie'), ('CD', 'Dostarczono'), ('SD', 'Wysłano')], default='PD', max_length=3),
        ),
    ]
