# Generated by Django 4.2.7 on 2024-01-18 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orderdetails_order_number_alter_orderdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('PG', 'Kompletowane'), ('CD', 'Dostarczono'), ('SD', 'Wysłano')], default='PG', max_length=3),
        ),
        migrations.CreateModel(
            name='Order1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_number', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('PG', 'Kompletowane'), ('CD', 'Dostarczono'), ('SD', 'Wysłano')], default='PG', max_length=3)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.client')),
            ],
        ),
    ]
